### PR TITLE
Add a Super Nintendo theme

### PR DESCRIPTION
**Pull request by christopherkenny**
Lots of greys and purples:

image

image

### CODE REVIEW

**Comment by lukepilling** [comment]
I love it but could you use the colours from the buttons for some of the discrete scale values or something? Otherwise it is quite uniform
super-nintendo-computer-game-controller-from-the-1990s-HH5T2E

**Comment by christopherkenny** [comment]
Those are there, they're just not used in the shorter discrete example. I've reordered them to avoid the double-purple.
<details> <summary> code for plot </summary> 

```
palette::palette(snes_palette) |> plot()
```
</details>

image

I think this makes the plot a little more vibrant:

image

What do you think?

**Comment by lukepilling** [comment]
Nice, looks much better to me

**Comment by MatthewBJane** [comment]
Awesome!!!

**Pull request merged**
